INSERT INTO TRAIN (TRAIN_ID, TRAIN_NAME, TRAIN_DESTINATION, TRAIN_DEPARTURE_DATE) VALUES('1','first','first direction','1970-01-01');
INSERT INTO TRAIN (TRAIN_ID, TRAIN_NAME, TRAIN_DESTINATION, TRAIN_DEPARTURE_DATE) VALUES('2','second','second direction','2020-02-02');
INSERT INTO TRAIN (TRAIN_ID, TRAIN_NAME, TRAIN_DESTINATION, TRAIN_DEPARTURE_DATE) VALUES('3','third','third direction','2020-03-03');

INSERT INTO PASSENGER (PASSENGER_ID, PASSENGER_NAME, TRAIN_ID) VALUES('1','Alfred','2');
INSERT INTO PASSENGER (PASSENGER_ID, PASSENGER_NAME, TRAIN_ID) VALUES('2','Bob','2');
INSERT INTO PASSENGER (PASSENGER_ID, PASSENGER_NAME, TRAIN_ID) VALUES('3','Chris','3');
INSERT INTO PASSENGER (PASSENGER_ID, PASSENGER_NAME, TRAIN_ID) VALUES('4','Derek','3');
INSERT INTO PASSENGER (PASSENGER_ID, PASSENGER_NAME, TRAIN_ID) VALUES('5','Ernest','3');
INSERT INTO PASSENGER (PASSENGER_ID, PASSENGER_NAME, TRAIN_ID) VALUES('6','Fidel','1');