DROP TABLE IF EXISTS TRAIN;
CREATE TABLE TRAIN
(
    TRAIN_ID INT NOT NULL AUTO_INCREMENT,
    TRAIN_NAME VARCHAR(128) NOT NULL UNIQUE,
    TRAIN_DESTINATION VARCHAR(128)
    TRAIN_DEPARTURE_DATE DATE
    PRIMARY KEY (TRAIN_ID)
);