INSERT INTO TRAIN (TRAIN_NAME, TRAIN_DESTINATION, TRAIN_DEPARTURE_DATE) VALUES('first','first direction','1970-01-01');
INSERT INTO TRAIN (TRAIN_NAME, TRAIN_DESTINATION, TRAIN_DEPARTURE_DATE) VALUES('second','second direction','2020-02-02');
INSERT INTO TRAIN (TRAIN_NAME, TRAIN_DESTINATION, TRAIN_DEPARTURE_DATE) VALUES('third','third direction','2020-03-03');